packages:
  - backend
  - frontend
  - chatbot

allowBuilds:
  argon2: false
  esbuild: false
  "@scarf/scarf": false
  '@google/genai': true
  protobufjs: true
  unrs-resolver: set this to true or false
