services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: mario_da_parfums
      POSTGRES_PASSWORD: mario_da_parfums
      POSTGRES_DB: mario_da_parfums
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
