// Catálogo único de códigos de error de validación de DTOs.
// Toda la aplicación (validators, wrappers, DTOs) debe importar los códigos
// desde acá en vez de usar strings sueltos, para que no existan dos códigos
// distintos para el mismo caso y el frontend pueda traducirlos sin ambigüedad.
// Ver docs/validation-error-codes.md para el detalle de cómo se usa este enum.
export enum ValidationErrorCode {
  // Genéricos: son los defaults de los wrappers en src/validators/wrappers.
  // Se usan tal cual cuando el campo no necesita un código más específico.
  FIELD_REQUIRED = 'FIELD_REQUIRED',
  INVALID_TYPE = 'INVALID_TYPE',
  INVALID_ENUM_VALUE = 'INVALID_ENUM_VALUE',
  MIN_LENGTH = 'MIN_LENGTH',
  MAX_LENGTH = 'MAX_LENGTH',
  CONTAINS_PROFANITY = 'CONTAINS_PROFANITY',

  // name
  NAME_REQUIRED = 'NAME_REQUIRED',
  NAME_INVALID_TYPE = 'NAME_INVALID_TYPE',
  NAME_TOO_LONG = 'NAME_TOO_LONG',

  // email
  EMAIL_REQUIRED = 'EMAIL_REQUIRED',
  EMAIL_INVALID_FORMAT = 'EMAIL_INVALID_FORMAT',

  // role
  ROLE_INVALID = 'ROLE_INVALID',

  // photoS3Key
  PHOTO_S3_KEY_INVALID_TYPE = 'PHOTO_S3_KEY_INVALID_TYPE',
  PHOTO_S3_KEY_INVALID_FORMAT = 'PHOTO_S3_KEY_INVALID_FORMAT',
  PHOTO_S3_KEY_TOO_LONG = 'PHOTO_S3_KEY_TOO_LONG',

  // password: presencia/tipo. Para las reglas de fortaleza ver PasswordErrorCode.
  PASSWORD_REQUIRED = 'PASSWORD_REQUIRED',
  PASSWORD_INVALID_TYPE = 'PASSWORD_INVALID_TYPE',

  // brand (fragrances)
  BRAND_REQUIRED = 'BRAND_REQUIRED',
  BRAND_INVALID_TYPE = 'BRAND_INVALID_TYPE',
  BRAND_TOO_LONG = 'BRAND_TOO_LONG',

  // concentration (fragrances)
  CONCENTRATION_INVALID_TYPE = 'CONCENTRATION_INVALID_TYPE',
  CONCENTRATION_TOO_LONG = 'CONCENTRATION_TOO_LONG',

  // description (fragrances)
  DESCRIPTION_INVALID_TYPE = 'DESCRIPTION_INVALID_TYPE',

  // imageUrl (fragrances)
  IMAGE_URL_INVALID_FORMAT = 'IMAGE_URL_INVALID_FORMAT',
  IMAGE_URL_TOO_LONG = 'IMAGE_URL_TOO_LONG',

  // vendor.name
  VENDOR_NAME_REQUIRED = 'VENDOR_NAME_REQUIRED',
  VENDOR_NAME_INVALID_TYPE = 'VENDOR_NAME_INVALID_TYPE',
  VENDOR_NAME_TOO_LONG = 'VENDOR_NAME_TOO_LONG',

  // vendor.websiteUrl
  VENDOR_WEBSITE_URL_REQUIRED = 'VENDOR_WEBSITE_URL_REQUIRED',
  VENDOR_WEBSITE_URL_INVALID_FORMAT = 'VENDOR_WEBSITE_URL_INVALID_FORMAT',
  VENDOR_WEBSITE_URL_TOO_LONG = 'VENDOR_WEBSITE_URL_TOO_LONG',

  // listing.fragranceId
  LISTING_FRAGRANCE_ID_REQUIRED = 'LISTING_FRAGRANCE_ID_REQUIRED',
  LISTING_FRAGRANCE_ID_INVALID_FORMAT = 'LISTING_FRAGRANCE_ID_INVALID_FORMAT',

  // listing.vendorId
  LISTING_VENDOR_ID_REQUIRED = 'LISTING_VENDOR_ID_REQUIRED',
  LISTING_VENDOR_ID_INVALID_TYPE = 'LISTING_VENDOR_ID_INVALID_TYPE',

  // listing.sizeMl
  LISTING_SIZE_ML_REQUIRED = 'LISTING_SIZE_ML_REQUIRED',
  LISTING_SIZE_ML_INVALID_TYPE = 'LISTING_SIZE_ML_INVALID_TYPE',

  // listing.price
  LISTING_PRICE_REQUIRED = 'LISTING_PRICE_REQUIRED',
  LISTING_PRICE_INVALID_TYPE = 'LISTING_PRICE_INVALID_TYPE',

  // listing.url
  LISTING_URL_REQUIRED = 'LISTING_URL_REQUIRED',
  LISTING_URL_INVALID_FORMAT = 'LISTING_URL_INVALID_FORMAT',
  LISTING_URL_TOO_LONG = 'LISTING_URL_TOO_LONG',

  // listing.inStock
  LISTING_IN_STOCK_INVALID_TYPE = 'LISTING_IN_STOCK_INVALID_TYPE',

  // favorite.fragranceId
  FRAGRANCE_ID_REQUIRED = 'FRAGRANCE_ID_REQUIRED',
  FRAGRANCE_ID_INVALID_FORMAT = 'FRAGRANCE_ID_INVALID_FORMAT',

  // favorite batch fragranceIds
  FRAGRANCE_IDS_REQUIRED = 'FRAGRANCE_IDS_REQUIRED',
}
